name: publish

on:
  push :
    branches:
      - 'develop'

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest

    permissions:
        contents: write
        packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the hello-docker Docker image
        run: |
          docker build . --tag ghcr.io/ptitjbus/devops-tp-initiation:staging
          docker push ghcr.io/ptitjbus/devops-tp-initiation:staging
      
      - name: Coveralls
        uses: coverallsapp/github-action@v2
